sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t dimbbass/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dimbbass/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-913221062928"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY